services:
  - type: web
    name: tirupur-garments
    runtime: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
