"""add translations columns

Revision ID: 38d119f9857a
Revises: e7d62059736f
Create Date: 2026-08-11 17:27:39.425608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d119f9857a'
down_revision = 'e7d62059736f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta_en', sa.String(length=255), nullable=True))

    with op.batch_alter_table('company_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta_en', sa.String(length=255), nullable=True))

    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('summary_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta_en', sa.String(length=255), nullable=True))

    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('summary_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta_en', sa.String(length=255), nullable=True))

    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))

    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name_ta_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_ta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_ta_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_title_ta_en', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description_ta_en', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('seo_description_ta_en')
        batch_op.drop_column('seo_description_ta')
        batch_op.drop_column('seo_title_ta_en')
        batch_op.drop_column('seo_title_ta')
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_column('seo_description_ta_en')
        batch_op.drop_column('seo_description_ta')
        batch_op.drop_column('seo_title_ta_en')
        batch_op.drop_column('seo_title_ta')
        batch_op.drop_column('content_ta_en')
        batch_op.drop_column('content_ta')
        batch_op.drop_column('summary_ta_en')
        batch_op.drop_column('summary_ta')
        batch_op.drop_column('title_ta_en')
        batch_op.drop_column('title_ta')

    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.drop_column('seo_description_ta_en')
        batch_op.drop_column('seo_description_ta')
        batch_op.drop_column('seo_title_ta_en')
        batch_op.drop_column('seo_title_ta')
        batch_op.drop_column('content_ta_en')
        batch_op.drop_column('content_ta')
        batch_op.drop_column('summary_ta_en')
        batch_op.drop_column('summary_ta')
        batch_op.drop_column('title_ta_en')
        batch_op.drop_column('title_ta')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('seo_description_ta_en')
        batch_op.drop_column('seo_description_ta')
        batch_op.drop_column('seo_title_ta_en')
        batch_op.drop_column('seo_title_ta')
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('title_ta_en')
        batch_op.drop_column('title_ta')

    with op.batch_alter_table('company_categories', schema=None) as batch_op:
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('seo_description_ta_en')
        batch_op.drop_column('seo_description_ta')
        batch_op.drop_column('seo_title_ta_en')
        batch_op.drop_column('seo_title_ta')
        batch_op.drop_column('address_ta_en')
        batch_op.drop_column('address_ta')
        batch_op.drop_column('description_ta_en')
        batch_op.drop_column('description_ta')
        batch_op.drop_column('name_ta_en')
        batch_op.drop_column('name_ta')

    # ### end Alembic commands ###
