"""initial migration

Revision ID: e7d62059736f
Revises: 
Create Date: 2026-08-11 16:13:48.124941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d62059736f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('company_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_categories_slug'), ['slug'], unique=True)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_categories_slug'), ['slug'], unique=True)

    op.create_table('news_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_categories_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_categories_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['company_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_status'), ['status'], unique=False)

    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_articles_status'), ['status'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_articles_status'), ['status'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tools_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('seo_title', sa.String(length=150), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('knowledge_tags',
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_id', 'tag_id')
    )
    op.create_table('news_tags',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'tag_id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_services_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_status'))
        batch_op.drop_index(batch_op.f('ix_services_slug'))
        batch_op.drop_index(batch_op.f('ix_services_provider_id'))

    op.drop_table('services')
    op.drop_table('news_tags')
    op.drop_table('knowledge_tags')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_slug'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_status'))
        batch_op.drop_index(batch_op.f('ix_tools_slug'))
        batch_op.drop_index(batch_op.f('ix_tools_created_at'))
        batch_op.drop_index(batch_op.f('ix_tools_category_id'))

    op.drop_table('tools')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_status'))
        batch_op.drop_index(batch_op.f('ix_news_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_category_id'))

    op.drop_table('news_articles')
    op.drop_table('media')
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_articles_category_id'))

    op.drop_table('knowledge_articles')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_status'))
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_created_at'))
        batch_op.drop_index(batch_op.f('ix_companies_category_id'))

    op.drop_table('companies')
    op.drop_table('admins')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_categories_slug'))

    op.drop_table('tool_categories')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('news_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_categories_slug'))

    op.drop_table('news_categories')
    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_categories_slug'))

    op.drop_table('knowledge_categories')
    op.drop_table('contact_messages')
    with op.batch_alter_table('company_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_categories_slug'))

    op.drop_table('company_categories')
    # ### end Alembic commands ###
